

services:
  db:
    image: postgres:15-alpine
    container_name: wa-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  wa-engine:
    build: .
    container_name: wa-filter-bot
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - TZ=America/Los_Angeles
    shm_size: '2gb'
    volumes:

      - ./wa_sessions:/usr/src/app/.wwebjs_auth

  wa-dashboard:
    build: .
    container_name: wa-filter-dashboard
    command: node dashboard.js
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"